paths:
  # location of the main sqlite db file
  db: "feeds.db"

daemon:
  # should run as daemon (required for http server to run)
  enabled: true
  # delay that daemon should wait between read/write attempts
  delay: 15

imap:
  # should imap syncronization be enabled
  enabled: true
  # imap host
  host: imap.gmail.com
  # imap port
  port: 993
  # imap username
  username: mymail@gmail.com
  # imap password
  password: mypass
  folder:
    # prefix to use when creating imap folders (RSS/myfolder)
    prefix: RSS
    # Should folder names be capitalized (by default everything is lowercase)
    capitalize: true
  # To field that will be used in email
  to:
    name: My Name
    email: mymail@gmail.com
  # From field that will be used in email
  from:
    # Name will be ignored if feed has author data
    name: RSS Bot
    email: rss@mail.com

# Print debug messages
debug: true

# RSS/Atom urls configuration
urls:
  rust:
  - http://blog.rust-lang.org/feed.xml
  nim:
  - http://nim-lang.org/news.xml
  clojure:
  - http://feeds.cognitect.com/blog/feed.rss
  - http://swannodette.github.com/atom.xml
  - http://blog.fikesfarm.com/feed.xml
  elixir:
  - http://feeds.feedburner.com/ElixirLang
  go:
  - https://blog.golang.org/feed.atom
