version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/app
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - run: go get
      - run: make
