name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: golang:alpine
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get

    - name: Build
      run: make
